### ISSUE TITLE
Limit shared TravisCI resource to 1 build per run #

### ISSUE THREAD

**Issue by bcullman** [SAP/ui5-server#115]
Because of the way TravisCI works with open source, the SAP org is limited to 5 concurrent jobs. This can prevent other repos from getting any resources for extended periods of time.

Would you be willing to look into changing the travis configuration so jobs run serially or limit the number of concurrent jobs, so that TravisCI resources can be distributed a bit more?

Additional context:
When one or two repos take all 5 concurrent jobs, it really becomes a bottleneck for other repos.

See the (admittedly aged) tweet here:

https://twitter.com/travisci/status/424990533447327744

Updated tweet confirming no change: https://twitter.com/mobot11/status/1083783900319559682

crossposted to: 
SAP/vulnerability-assessment-tool#79
SAP/cloud-commerce-spartacus-storefront#868
SAP/chevrotain/issues/878

**Comment by RandomByte** [comment]
We pretty much share @bd82's opinion stated [here](https://github.com/SAP/vulnerability-assessment-tool/issues/79#issuecomment-454887024) and [here](https://github.com/SAP/chevrotain/issues/878#issuecomment-454883730).

If your project heavily relies on fast build times, there's nothing stopping you from using any of the various payed CI/CD services that are out there. SAPs Open Source Program Office or the SAP org owners can probably support you with that (CC @jonathanbaker7).

Mostly, we are concerned that by reducing the number of concurrent jobs for a repository, the runtime of a single build could increase by a factor of five. The same goes for all other repositories that set this limit. The result would be longer builds for everyone. The only difference is that they may *start* earlier.

Moreover, our Travis org is idle many times throughout the day. As I'm typing this it is changing from being completely idle to running one build.  
Limiting the number of concurrent jobs would now leave a new PR with an unnecessary long build time and idle Travis jobs. I think that with the configuration offered by Travis, it is hard to keep a balance between using and distributing the available resources efficiently. I think their answer to this kind of problem is buying more resources 🙂

This repository is part of the [UI5 Build and Development Tooling](https://github.com/SAP/ui5-tooling), which consists of **seven** individual repositories.  
Most of our travis builds are currently related to **releases** of our modules and **dependency updates** done by @dependabot. Both is typically happening in multiple repositories simultaneously. Limiting concurrent jobs per repository wont't have much effect on the overall load of our Travis org in these cases.

### Actions on our side (UI5 Tooling)
**Regarding releases:**  
We are working on improving our release process. This will also include moving the load it currently puts on Travis to SAP internal or other thirdparty (Azure?) infrastructure. There is no timeline for this.

**Regarding dependency updates:**  
We limited dependabot to update dependencies once a day, at 5am UTC (9pm PST). Starting today.

**Comment by bcullman** [comment]
have a look at

https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/933/files

they dropped 5-7 min off build time with a few optimizations.
