### ISSUE TITLE
git dependency in package.json

### ISSUE THREAD

**Issue by amiramw** [SAP/ui5-server#16]
It seems that ui5-server is dependent on github:RandomByte/serve-index#fs-option.

https://github.com/SAP/ui5-server/blob/master/package.json#L105

This is problematic in Web IDE where git dependency is not supported in npm.
Is is possible to eliminate the dependency?

**Comment by RandomByte** [comment]
This is a fork of [expressjs/serve-index](https://github.com/expressjs/serve-index) that adds interoperability with the virtual-fs of [ui5-fs](https://github.com/SAP/ui5-fs).

As a generic solution in expressjs/serve-index seems quite challenging (see [serve-index #67](https://github.com/expressjs/serve-index/pull/67)) we are currently evaluating whether we'll go with a fork like the one currently used or with a custom index listing implementation.

**Comment by petermuessig** [comment]
Pull request would be good to go - @RandomByte @matz3 assigned as reviewers to hopefully approve my first contribution to the UI5 build and development tools... ;-)

**Comment by amiramw** [comment]
On which version of @ui5/cli will the fix be available?

**Comment by RandomByte** [comment]
Released with @ui5/server [v0.1.1](https://github.com/SAP/ui5-server/releases/tag/v0.1.1).

@ui5/cli should automatically choose that version when installing
