### ISSUE TITLE
app instance is needed in custom middleware

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/ui5-server#240]
Hi!

Writing a custom middleware sometimes it is important to deliver several rules at once encapsulating all the logic inside the module.

One of key APIs in this case is express app instance which we can app.use().

Even having it as req.app - declaring routes during a first request handling  can be already too late - all new requests will be added to the end of the route stack and middle-ware tree will be ignored.

I've created a proposal here: https://github.com/SAP/ui5-server/pull/239

Here is an approximate example of middleware using app api.

https://gitlab.com/theplenkov-npm/ui5-fiori-sandbox/blob/master/fioriSandbox.js

**Comment by matz3** [comment]
The provided GitLab link seems to require authentication (`You need to sign in or sign up before continuing.`). Maybe the repository is private?

I would first like to understand what you would like to achieve.
Apart from that I already have something in mind for a more flexible plugin API to include/register extensions, not only for middleware but also for tasks and more. However this is probably something for a 2.0.

**Comment by ThePlenkov** [comment]
Hi @matz3 . I'm sorry - it was private. I opened it.

Here is approximate way how I would love to write a middleware plugin:
```json
module.exports = async function ({ resources, options, app }) {
  app.get('/',redirectToFLP)
  app.use('/opu/odata', nocache)
  app.use('/appconfig/', express.static('/appconfig') )
  options.configurations.destinations.forEach(dest = > app.use(dest.path, proxy(dest.proxy) ))
}
```

**Comment by ThePlenkov** [comment]
> Apart from that I already have something in mind for a more flexible plugin API to include/register extensions, not only for middleware but also for tasks and more. However this is probably something for a 2.0.

With my PR it will be already possible to achieve in the current version if we can expose app in the middleware. Again - it's even possible now, by taking req.app during a first call, but at this moment the express route stack is full and all new app.use calls will go to the end which goes across to ui5.yaml spec

**Comment by matz3** [comment]
Afaics this can already be achieved by using the [express.Router()](https://expressjs.com/en/guide/routing.html#express-router).

```js
const express = require("express");

module.exports = function ({ resources, options }) {
    const app = express.Router();

    // app.use(...)

    return app;
};
```

So I currently don't see a technical reason to expose the `app` instance. Or did I miss something?

**Comment by ThePlenkov** [comment]
OK - i didn't know that. So you want to say it's same instance - not another one? Then it's not an issue actually))

**Comment by matz3** [comment]
No, that's not the same instance. You can nest routers as "mini-apps" to structure your sever middleware. So it's a convenient way to expose multiple middleware functions as one. After all they will be registered within the "app" which is internally managed by the ui5-server.

**Comment by ThePlenkov** [comment]
@matz3 I tried your approach - and it didn't work work for me. Yes - I could create and use a new app instance.

But even my middleware is called first - it was rewritten by standard UI5 server middleware.

I.e. I want a route page to be redirected and I declare
```js
app.get("/", async (req, res) => {
        res.redirect(homePage);
    });
```

but in this case i do not have any redirection. Because standard serveIndex controls the root and renders resources page.

I could achieve my goal only by using the app instance from above.

**Comment by matz3** [comment]
Not sure what your code looks like, but this worked for me:
https://github.com/matz3/openui5-sample-app/commit/d4a2445ec42a7bbc89f54492d3dfc09e3147d9de (https://github.com/matz3/openui5-sample-app/tree/middleware-express-router)

**Comment by ThePlenkov** [comment]
Ok - I see what I did wrong! I forgot to return app instance. Thank you.

**Comment by matz3** [comment]
No worries 👍
