### ISSUE TITLE
[Feature] Have the ability to manage server cache

### ISSUE THREAD

**Issue by jberthe** [SAP/ui5-server#313]
Is there any possiblities to manage the server cache ? When we test an application in flpLaunchpad locally, it call all the time the UI5 resouces and it take lot of time.

It would be nice to set a cache mechanisme to manage it.

## Affected components *(if known)*

- [X] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
What is your expectation specifically? The ui5-server already sets etag headers, 
so for unchanged resources should be cached already.

However, the client still needs to check whether a resource has changed and therefore always sends a conditional GET request for every resource. For unchanged resources, the server just sends an empty 304 response. These requests still take time.

An improvement might be to automatically bundle (framework) dependencies to reduce the number of files requested. Also see https://github.com/SAP/ui5-server/issues/47

**Comment by RandomByte** [comment]
I'm closing this issue as stale as we need more information from the reporter.
