### ISSUE TITLE
Error when 'npm run start': middlewareRepository: Unknown Middleware ui5-middleware-simpleproxy

### ISSUE THREAD

**Issue by kepair** [SAP/ui5-server#339]
## Expected Behavior
After generating a List report (v2 or v4), I can run it locally with `npm run start`.

## Current Behavior
`npm run start` throws an error:

```
Error Message:
middlewareRepository: Unknown Middleware ui5-middleware-simpleproxy

Stack Trace:
Error: middlewareRepository: Unknown Middleware ui5-middleware-simpleproxy
    at Object.getMiddleware (C:\Users\...\GitHub\admin-ui\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\middlewareRepository.js:19:9)
    at MiddlewareManager.addMiddleware (C:\Users\...\GitHub\admin-ui\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:39:47)
    at MiddlewareManager.addCustomMiddleware (C:\Users\...\GitHub\admin-ui\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:187:15)
    at MiddlewareManager.applyMiddleware (C:\Users\...\GitHub\admin-ui\node_modules\@ui5\cli\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:27:14)
    at async Object.serve (C:\Users\...\GitHub\admin-ui\node_modules\@ui5\cli\node_modules\@ui5\server\lib\server.js:137:3)
    at async Object.serve.handler (C:\Users\...\GitHub\admin-ui\node_modules\@ui5\cli\lib\cli\commands\serve.js:120:33)
```

## Steps to reproduce the issue
1. Use the Application generator to create a List report
2. As service, I tried using a local metadata for v2, and a CAP service running locally for v4
3. After fixing some dependencies (see [issue](https://github.com/SAP/ui5-tooling/issues/241) in ui5 tooling), execute `npm run start`

## Context
- UI5 Module Version : 2.0.3
- Node.js Version: 12.16.1
- npm Version: 6.13.4
- OS/Platform: Windows 10
- IDE: vscode

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [X] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

Kind regards,
Pedro

**Comment by vobu** [comment]
have you added `ui5-middleware-simpleproxy` to `ui5.dependencies` in package.json?

**Comment by RandomByte** [comment]
> Use the Application generator to create a List report

Which application generator are you referring to?

**Comment by kepair** [comment]
Hi,

The application generator I'm referring to is the: SAP Fiori tools - Application Generator.
I have `ui5-middleware-simpleproxy`, in `ui5.dependencies` in package.json.

My package.json:
```
{
	"name": "admin-ui",
	"version": "0.0.1",
	"private": true,
	"sapux": true,
	"description": "This is my new Fiori elements application",
	"keywords": [
		"ui5",
		"openui5",
		"sapui5"
	],
	"main": "webapp/index.html",
	"scripts": {
		"start": "ui5 serve --open index.html#fe-lrop-v4 --",
		"build": "rimraf dist && ui5 build -a --include-task=generateManifestBundle generateCachebusterInfo",
		"deploy": "fiori add deploy-config"
	},
	"remarkConfig": {
		"plugins": [
			"remark-preset-lint-consistent"
		]
	},
	"devDependencies": {
		"@sap/ux-specification": "^1.76.8",
		"@sap/ux-ui5-tooling": "^1.0.6",
		"@ui5/cli": "2.0.3",
		"@ui5/fs": "2.0.1",
		"@ui5/logger": "2.0.0",
		"rimraf": "3.0.0"
	},
	"optionalDependencies": {
		"fsevents": "1.2.9"
	},
	"ui5": {
		"dependencies": [
			"@sap/ux-ui5-tooling",
			"ui5-middleware-simpleproxy"
		]
	},
	"dependencies": {
		"ui5-middleware-simpleproxy": "0.3.2"
	}
}

```

Kind regards,
Pedro

**Comment by RandomByte** [comment]
The package.json is looking good. Could you please execute `npm install` in your project once again? Just to make sure all dependencies are in place.

**Comment by kepair** [comment]
Sure,

This is the result:

```
npm WARN request-promise-core@1.1.3 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-native@1.0.8 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.       
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\@ui5\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1032 packages in 5.163s

31 packages are looking for funding
  run `npm fund` for details

found 19 vulnerabilities (17 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
There were more low vulnerabilities before, I also ran npm audit fix.

The result is the same.

Thanks in advance.

Kind regards,
Pedro

**Comment by RandomByte** [comment]
Hm, I tried this setup with your package.json locally and can't reproduce the error. Could you please also share the content of the `ui5.yaml` located next to the package.json?

**Comment by kepair** [comment]
Hi,

Sure, here it is:

```
specVersion: '1.0'
metadata:
  name: admin-ui
type: application
ui5Version: 
ui5Theme: sap_fiori_3
server:
  customMiddleware:
  - name: ui5-middleware-simpleproxy
    afterMiddleware: compression
    mountPath: [ /webinar, /resources, /test-resources ]
    configuration:
      baseUri: http://localhost:4004
      ui5Uri: https://sapui5.hana.ondemand.com
      ui5Version: 
  - name: ui5-app-reloader
    afterMiddleware: compression
    configuration:
     port: 35729
     path: webapp
```

**Comment by RandomByte** [comment]
With this configuration I get the following error:

```
⚠️  Process Failed With Error

Error Message:
middlewareRepository: Unknown Middleware ui5-app-reloader
```

Which is different from the error you [reported](https://github.com/SAP/ui5-server/issues/339#issue-654685088).

Can you please confirm which error you are currently facing?

**Comment by kepair** [comment]
You are right,

I get :

```
⚠️  Process Failed With Error

Error Message:
middlewareRepository: Unknown Middleware ui5-app-reloader
```

**Comment by RandomByte** [comment]
Alright 👍 

This error is thrown because your project has no dependency to a custom middleware named "ui5-app-reloader". I don't know this middleware, and it is [not available on npm](https://www.npmjs.com/search?q=ui5-app-reloader). But the configuration seems similar to that of the [ui5-middleware-livereload](https://www.npmjs.com/package/ui5-middleware-livereload), so you could switch to that. Alternatively, you can also remove the custom middleware configuration and the server should start up just fine.

If this configuration was part of the generated app, you can also reach out to the Fiori tools project as explained in my [comment here](https://github.com/SAP/ui5-tooling/issues/241#issuecomment-656683092).

Since this is not an issue with the standard ui5-server module, I'll close this incident. Thanks for reaching out and working with the tooling!
